### ISSUE TITLE
Running specs does not work

### ISSUE THREAD

**Issue by stschulte** [nanliu/puppet-solaris#1]
Hi Nan,

I've forked your repo but unfortunately I am not able to run the specs.

```
cannot load such file -- spec_helper (LoadError)
```

Am I missing something in my `RUBYLIB` path?

**Comment by nanliu** [comment]
Apparently forgot to include it, I've added the spec_helper and fixtures directory. Might have a few extras, but I think the spec test should run now.

**Comment by nanliu** [comment]
See #2.
